### PR TITLE
Add junit test

### PR DESCRIPTION
**Pull request by tisoft**

### CODE REVIEW

**Comment by tisoft** [comment]
Playing around with unit tests.

Mac OS works out of the box, currently truing to get a valid context in linux. Don't know if Windows is possible.

**Comment by tisoft** [comment]
Screenshots of the results are attached as artifacts (for example: https://github.com/LWJGLX/lwjgl3-awt/actions/runs/327701370)

Example of Mac OS:
Mac OS X_test

**Comment by tisoft** [comment]
Linux works, too

image

**Comment by tisoft** [comment]
Aaaand Windows:

image

Windows Server 2019 does not work out of the box, so I am replacing the opengl32.dll with mesa. The error message with "native" OpenGL is `Extended context attributes requested but WGL_ARB_create_context is unavailable`

**Comment by tisoft** [comment]
Image comparing works. Mac Os fails as expected due to #29

**Comment by tisoft** [comment]
I frankensteinend together JNA, java-objc-bridge and the Lwjgl JAWT stuff. I could get rid of the call to the embedded dylib with that and could also fix the positioning.

trying now to get rid of JNA and java-objc-bridge again. 🤷

**Comment by tisoft** [comment]
Have it working now by modifying the embedded dylib. I have also added instructions on how to recompile the dylib without creating a full blown Xcode project. We could also add the dylib building to the GitHub action.

We can get rid of the custom dylib by using JNA and java-objc-bridge. But that pulls in those dependencies just for that single call. The problem with the LWJGL JNI Bindings is, that the CGRect struct needs to be passed by value and that is not supported. I also tried to use the DynCall Class and fake the CGRect structure by pushing 4 doubles on the call stack, but that didn't work either. So until LWJGL/DynCall adds support for pass by value structures, I think we should keep our custom dylib.

**Comment by httpdigest** [comment]
Thanks a lot!

**Pull request merged**
