### PR TITLE
Add support for setting the GL version and other GL attributes for Linux.

### PR DESCRIPTION
**Pull request by aschleck**

### CODE REVIEW

**Comment by aschleck** [comment]
No idea why CI failed, but I think it has nothing to do with this patch!

**Comment by httpdigest** [comment]
Closed due to unresponsiveness towards review findings/comments.

**Comment by aschleck** [comment]
Hi @httpdigest, sorry I didn't see this earlier. This is my first real pull request, where are the review findings or comments? I found that I had to install the Travis CI app, and that seems to be passing for me now. Are there other things I missed? I would like to re-pull request once I address your concerns as I think my change has value.

**Comment by httpdigest** [comment]
Oh, sorry, it was probably my fault. I had written a comment but likely failed to "submit" the review. Please do a new PR.

**Pull request closed without merging**
