### PR TITLE
Remove native createMTKView function, replace with non-native code

### PR DESCRIPTION
**Pull request by skalarproduktraum**
This PR (kinda) continues #55, and intends to remove the native blob so far necessary on macOS.

It currently does not fully work, related to the issue that lwjgl's JNI functions do not allow passing the NSRect by-value, only by-reference.

- [X] Implement and test non-native approach for Vulkan
- [x] Implement and test non-native approach for OpenGL (essentially mostly replicating the code for Vulkan)
- [ ] Update ClearScreenDemo to not use the dinosaur version I've used so far (thanks for the pointer, @httpdigest 👍 )

### CODE REVIEW

**Comment by skalarproduktraum** [comment]
That went quicker than expected! MTKView creation now works via libffi, thanks to a pointer (no pun intended) from @httpdigest 👍 

This is what the ClearScreenDemo now looks like:

Screenshot 2022-06-10 at 18 14 20

Didn't have a chance yet to test this with our application, but this is seriously looking good. Maybe @SWinxy  wants to have a look? So far I've only implemented the view creation for Vulkan, but using that code doing the same for OpenGL is straightforward. It'd just be great if #51 could be fixed before that :-/

**Comment by skalarproduktraum** [comment]
I guess that progress also kinda obsoletes #55 ...

**Comment by SWinxy** [comment]
Nice. I'll look at it tomorrow—bug me about it if I forget.

**Comment by skalarproduktraum** [comment]
@SWinxy, I hereby 🐞 you 😅

**Comment by SWinxy** [comment]
Looks awesome! I've gotten the Vulkan demos + my own application working on my M1 Mac. I'll update you when I figure out what my Intel Mac is doing...

**Comment by SWinxy** [comment]
On my radar again. Will look closer later.

**Comment by Hc747** [comment]
Bump @SWinxy 👀

**Comment by skalarproduktraum** [comment]
@Hc747 If you already want to give this a shot, you can do so via [jitpack.io](https://jitpack.io), see the docs at https://docs.jitpack.io - the GroupID:artifact:version string you'll need is `com.github.skalarproduktraum:lwjgl3-awt:d7a7369`, that refers to the latest commit on my PR/branch 👍

**Comment by Hc747** [comment]
> @Hc747 If you already want to give this a shot, you can do so via [jitpack.io](https://jitpack.io), see the docs at https://docs.jitpack.io - the GroupID:artifact:version string you'll need is `com.github.skalarproduktraum:lwjgl3-awt:d7a7369`, that refers to the latest commit on my PR/branch 👍

Hi there - thank you so much for getting back to me! On your Jitpack build, I receive the following issue within the static initialiser of `PlatformMacOSXGLCanvas` at line 79.
```java
        Library.loadSystem("org.lwjgl.awt", "lwjgl3awt");
```
```
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl3awt.dylib
	at org.lwjgl.system.Library.loadSystem(Library.java:164)
	at org.lwjgl.system.Library.loadSystem(Library.java:63)
	at org.lwjgl.opengl.awt.PlatformMacOSXGLCanvas.<clinit>(PlatformMacOSXGLCanvas.java:79)
	at org.lwjgl.opengl.awt.AWTGLCanvas.createPlatformCanvas(AWTGLCanvas.java:29)
	at org.lwjgl.opengl.awt.AWTGLCanvas.<init>(AWTGLCanvas.java:20)
```
This is on an ARM64 M1 Mac, if that is any help!

**Comment by SWinxy** [comment]
I've taken a look at these changes, and I am very impressed.

Before this is merged, I ask a few things:

1. Rebase your commits on top of the current main branch. There are POM issues that have since been fixed.
2. There is a line of code in `AWT.java` (ln 116) that checks if the platform is macOS ARM. Please change it to `Platform.get() == Platform.MACOSX ||` so that it will not fail.
3. Remove debug printing for production use

One other note, and something we can ignore: ClearScreenDemo causes issues with x86 macs. I'm not sure what it is, but it's not too big of an issue since the SimpleDemo and my application both work without issue.

Once those things are fixed, I'll squash and merge. Be ready! :)

**Comment by Hc747** [comment]
Keen! Thank you all! :)

**Comment by skalarproduktraum** [comment]
Done, @SWinxy! Let me know if you need anything else 👍

**Comment by SWinxy** [comment]
!!!

**Comment by skalarproduktraum** [comment]
Thank you, @SWinxy, it was very nice working with you on this 👍

**Comment by SiboVG** [comment]
Thank you for your work @skalarproduktraum @SWinxy!!

**Pull request merged**
