### PR TITLE
Altered switch statements (& unboxed int to string conversion)

### PR DESCRIPTION
**Pull request by SWinxy**
AWTVKCanvas class currently loads the class by a string, rather than doing it right in the switch statement (why was this done?). The Vulkan demo had else-if statements, and would benefit from using a switch for cleanliness sake. I also removed `Integer.valueOf()` in the `VKUtil.java` class.

### CODE REVIEW

**Comment by SWinxy** [comment]
Pinging @httpdigest. Dunno if you have seen this yet.

**Comment by httpdigest** [comment]
Could you please rebase? That merge commit shouldn't be necessary and I would like to avoid such "noise" in the commit history.

**Comment by SWinxy** [comment]
OK I think I got it. Sorry about that. lmk if there's other things you want me to do.

**Comment by SWinxy** [comment]
OK I think I got it. Sorry about that. lmk if there's other things you want me to do.

**Comment by httpdigest** [comment]
Thanks!

**Comment by SWinxy** [comment]
Eyyy thanks Kai.

**Pull request merged**
